### ISSUE TITLE
Local float parsing Error!

### ISSUE THREAD

**Issue by UnknownEnergy** [CoolBitX-Technology/coolwallet-android#1]
Hi i found an issue for users that have a different local float formatting than this one: 123.56
Germany and Austria are having this formatting: 123,56 (with , not dot)
It caused the app to crash completely without beeing able to use the Transaction Fee change functionality

So i fixed this issues like that:
public float parseStringToFloatInternational(String str)
    {
        NumberFormat format = NumberFormat.getInstance(Locale.getDefault());
        Number number = null;
        try {
            number = format.parse(str);
        } catch (ParseException e) {
            e.printStackTrace();
            LogUtil.e("edtFee parsing error! "+e.getMessage());
        }
        return number.floatValue();
    }

instead of: Float.valueOf(edtFee.getText().toString()

I also saw that TrxBlks.java bean and some drawables like @drawable/linearlayout_stroke are missing on git.

I am not able to push changes so i wrote it here.

**Comment by yobum** [comment]
Thank you @UnknownEnergy !
